default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['SIMPLE_SERVER_DATABASE_HOST'] %>
  username: <%= ENV['SIMPLE_SERVER_DATABASE_USERNAME'] %>
  password: <%= ENV['SIMPLE_SERVER_DATABASE_PASSWORD'] %>
  database: <%= ENV['SIMPLE_SERVER_DATABASE_NAME'] %>

development:
  <<: *default
  host: localhost
  database: simple-server_development
  username: postgres
  password: simple

test:
  <<: *default
  host: localhost
  database: simple-server_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: postgres
  password: simple

production:
  <<: *default
  host: localhost
  database: simple-server
  username: postgres
  password: simple
